/* Generated By:JJTree: Do not edit this line. /Users/jalkanen/Eclipse/priha/src/generated-sources/org/priha/query/aqt/xpath/XPathVisitor.java */

package org.priha.query.aqt.xpath;

public interface XPathVisitor
{
  public Object visit(SimpleNode node, Object data);
}
