/* Generated By:JavaCC: Do not edit this line. XPathVisitor.java Version 4.1 */
package org.priha.query.aqt.xpath;

public interface XPathVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=d2aa3b61d380a4f8e498112a902ac4c7 (do not edit this line) */
